/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class faceTag_recognizer_RecognizerInterface */

#ifndef _Included_faceTag_recognizer_RecognizerInterface
#define _Included_faceTag_recognizer_RecognizerInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     faceTag_recognizer_RecognizerInterface
 * Method:    detectForRectangles
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[LfaceTag/entities/Rectangle;
 */
JNIEXPORT jobjectArray JNICALL Java_faceTag_recognizer_RecognizerInterface_detectForRectangles
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
